apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaConnector
metadata:
  name: aws-sink-connector
  labels:
    strimzi.io/cluster: k8s-connect-cluster
spec:
  class: io.confluent.connect.s3.S3SinkConnector
  tasksMax: 1
  pause: false
  autoRestart:
    enabled: true
  config:
    tasks.max: 1
    topics: institucionaldb.stg_institucional.acq_cofusers,institucionaldb.stg_institucional.acq_mcc
    transforms: unwrap,renameField
    transforms.unwrap.type: io.debezium.transforms.ExtractNewRecordState
    transforms.unwrap.add.fields: ts_ms
    transforms.unwrap.delete.handling.mode: rewrite
    transforms.renameField.type: org.apache.kafka.connect.transforms.ReplaceField$Value
    transforms.renameField.renames: __ts_ms:timestamp,__deleted:deleted
    format.class: io.confluent.connect.s3.format.json.JsonFormat
    flush.size: 1000
    partition.duration.ms: 60000
    rotate.interval.ms: 60000
    rotate.schedule.interval.ms: 600000
    s3.bucket.name: <bucket-name>
    s3.region: us-east-1
    aws.access.key.id: ${secrets:kafka/aws-credentials:accessKeyId}
    aws.secret.access.key: ${secrets:kafka/aws-credentials:secretAccessKey}
    storage.class: io.confluent.connect.s3.storage.S3Storage
    topics.dir: data
    partitioner.class: io.confluent.connect.storage.partitioner.TimeBasedPartitioner
    path.format: YYYY/MM/dd/HH/mm
    locale: pt_BR
    timezone: UTC
    timestamp.extractor: RecordField
    timestamp.field: timestamp
