kind: ConfigMap
apiVersion: v1
metadata:
  namespace: kafka
  name: {{ .Values.name }}
data:
  QUARKUS_PROFILE: prod
  KAFKA_BOOTSTRAP_SERVERS: {{ .Values.bootstrapServers }}
  APPLICATION_ID: registry_id
  REGISTRY_KAFKA_COMMON_SECURITY_PROTOCOL: SASL_SSL
  REGISTRY_KAFKA_COMMON_SASL_MECHANISM: SCRAM-SHA-512
  REGISTRY_KAFKA_COMMON_SASL_JAAS_CONFIG: org.apache.kafka.common.security.scram.ScramLoginModule required username="{{ .Values.kafkaUsername }}" password="{{ .Values.kafkaPassword }}";
