kind: Deployment
apiVersion: apps/v1
metadata:
  namespace: kafka
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: apicurio/apicurio-registry-kafkasql:latest-release
        envFrom:
        - configMapRef:
            name: {{ .Values.name }}
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 300M
          limits:
            memory: 300M
        livenessProbe:
            httpGet:
              path: /health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 8080
            scheme: HTTP
          initialDelaySeconds: 5
          timeoutSeconds: 5
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 3