version: '2'

services:
  # this is our kafka cluster.
  kafka-cluster:
    image: landoop/fast-data-dev:latest
    environment:
      ADV_HOST: 127.0.0.1         # Change to 192.168.99.100 if using Docker Toolbox
      RUNTESTS: 0                 # Disable Running tests so the cluster starts faster
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_DELETE_TOPIC_ENABLE: "true"
      KAFKA_COMPRESSION_TYPE: lz4
      KAFKA_DEFAULT_REPLICATION_FACTOR: 1
      KAFKA_NUM_PARTITIONS: 1
      DISABLE: debezium-postgres,debezium-mysql,elasticsearch,elastic5,elastic,mongodb,debezium-mongodb
    volumes:
      - "./connectors/debezium-connector-mysql:/connectors/debezium-connector-mysql"
      - "./connectors/debezium-connector-postgres:/connectors/debezium-connector-postgres"
      - "./connectors/elasticsearch-sink-connector:/connectors/elasticsearch-sink-connector"
      - "./connectors/mongo-source-sink-connector:/connectors/mongo-source-sink-connector"
      - "./connectors/jdbc-source-sink-connector:/connectors/jdbc-source-sink-connector"
      - "./connectors/azure-blob-sink-connector:/connectors/azure-blob-sink-connector"
    ports:
      - 2181:2181                 # Zookeeper
      - 3030:3030                 # Landoop UI
      - 8081-8083:8081-8083       # REST Proxy, Schema Registry, Kafka Connect ports
      - 9581-9585:9581-9585       # JMX Ports
      - 9092:9092                 # Kafka Broker

  mysql:
    image: quay.io/debezium/example-mysql:2.3
    environment:
      MYSQL_USER: mysqluser
      MYSQL_PASSWORD: mysqlpw
      MYSQL_ROOT_PASSWORD: debezium
    ports:
      - "3306:3306"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      ES_JAVA_OPTS: "-Xms1g -Xmx1g"
      discovery.type: "single-node"
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch

  mongo:
    image: mongodb/mongodb-community-server
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    ports:
      - "27017:27017"

  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
